# Try to find the OGG library
#  OGG_FOUND - system has OGG
#  OGG_INCLUDE_DIR - the OGG include directory
#  OGG_LIBRARY - the OGG library

FIND_PATH(OGG_INCLUDE_DIR NAMES ogg/ogg.h)
SET(_OGG_STATIC_LIBS libogg.a)
SET(_OGG_SHARED_LIBS libogg.dll.a ogg)
IF(MSVC)
    SET(_VCPKG_HINT "${CMAKE_BINARY_DIR}/vcpkg_installed/x64-windows-static/lib")
ELSE()
    SET(_VCPKG_HINT "")
ENDIF()
IF(USE_STATIC_LIBS)
    FIND_LIBRARY(OGG_LIBRARY NAMES ${_OGG_STATIC_LIBS} ${_OGG_SHARED_LIBS} HINTS ${_VCPKG_HINT})
ELSE()
    FIND_LIBRARY(OGG_LIBRARY NAMES ${_OGG_SHARED_LIBS} ${_OGG_STATIC_LIBS} HINTS ${_VCPKG_HINT})
ENDIF()
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OGG DEFAULT_MSG OGG_LIBRARY OGG_INCLUDE_DIR)
MARK_AS_ADVANCED(OGG_LIBRARY OGG_INCLUDE_DIR)