# Try to find the OpenSSL library
#  OPENSSL_FOUND - system has OpenSSL
#  OPENSSL_INCLUDE_DIR - the OpenSSL include directory
#  OPENSSL_LIBRARIES - the OpenSSL libraries (ssl + crypto)

FIND_PATH(OPENSSL_INCLUDE_DIR NAMES openssl/ssl.h PATH_SUFFIXES openssl-1.0)

IF(MSVC)
    SET(_VCPKG_LIB "${CMAKE_BINARY_DIR}/vcpkg_installed/x64-windows-static/lib")
    SET(_VCPKG_LIB_DEBUG "${CMAKE_BINARY_DIR}/vcpkg_installed/x64-windows-static/debug/lib")
    FIND_LIBRARY(OPENSSL_LIBRARY_RELEASE NAMES libssl.lib libssl HINTS ${_VCPKG_LIB} NO_DEFAULT_PATH)
    FIND_LIBRARY(OPENSSL_LIBRARY_DEBUG NAMES libssl.lib libssl HINTS ${_VCPKG_LIB_DEBUG} NO_DEFAULT_PATH)
    FIND_LIBRARY(OPENSSL_CRYPTO_LIBRARY_RELEASE NAMES libcrypto.lib libcrypto HINTS ${_VCPKG_LIB} NO_DEFAULT_PATH)
    FIND_LIBRARY(OPENSSL_CRYPTO_LIBRARY_DEBUG NAMES libcrypto.lib libcrypto HINTS ${_VCPKG_LIB_DEBUG} NO_DEFAULT_PATH)

    IF(OPENSSL_LIBRARY_RELEASE AND OPENSSL_LIBRARY_DEBUG)
        SET(OPENSSL_LIBRARY optimized ${OPENSSL_LIBRARY_RELEASE} debug ${OPENSSL_LIBRARY_DEBUG})
    ELSEIF(OPENSSL_LIBRARY_RELEASE)
        SET(OPENSSL_LIBRARY ${OPENSSL_LIBRARY_RELEASE})
    ELSE()
        SET(OPENSSL_LIBRARY ${OPENSSL_LIBRARY_DEBUG})
    ENDIF()
    IF(OPENSSL_CRYPTO_LIBRARY_RELEASE AND OPENSSL_CRYPTO_LIBRARY_DEBUG)
        SET(OPENSSL_CRYPTO_LIBRARY optimized ${OPENSSL_CRYPTO_LIBRARY_RELEASE} debug ${OPENSSL_CRYPTO_LIBRARY_DEBUG})
    ELSEIF(OPENSSL_CRYPTO_LIBRARY_RELEASE)
        SET(OPENSSL_CRYPTO_LIBRARY ${OPENSSL_CRYPTO_LIBRARY_RELEASE})
    ELSE()
        SET(OPENSSL_CRYPTO_LIBRARY ${OPENSSL_CRYPTO_LIBRARY_DEBUG})
    ENDIF()
ELSE()
    SET(_OPENSSL_STATIC_LIBS libssl.a)
    SET(_OPENSSL_SHARED_LIBS libssl.dll.a ssl)
    SET(_OPENSSL_CRYPTO_STATIC_LIBS libcrypto.a)
    SET(_OPENSSL_CRYPTO_SHARED_LIBS libcrypto.dll.a crypto)
    IF(USE_STATIC_LIBS)
        FIND_LIBRARY(OPENSSL_LIBRARY NAMES ${_OPENSSL_STATIC_LIBS} ${_OPENSSL_SHARED_LIBS})
        FIND_LIBRARY(OPENSSL_CRYPTO_LIBRARY NAMES ${_OPENSSL_CRYPTO_STATIC_LIBS} ${_OPENSSL_CRYPTO_SHARED_LIBS})
    ELSE()
        FIND_LIBRARY(OPENSSL_LIBRARY NAMES ${_OPENSSL_SHARED_LIBS} ${_OPENSSL_STATIC_LIBS})
        FIND_LIBRARY(OPENSSL_CRYPTO_LIBRARY NAMES ${_OPENSSL_CRYPTO_SHARED_LIBS} ${_OPENSSL_CRYPTO_STATIC_LIBS})
    ENDIF()
ENDIF()

SET(OPENSSL_LIBRARIES ${OPENSSL_LIBRARY} ${OPENSSL_CRYPTO_LIBRARY})
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENSSL DEFAULT_MSG OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR)
MARK_AS_ADVANCED(OPENSSL_LIBRARIES OPENSSL_LIBRARY OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR
                 OPENSSL_LIBRARY_RELEASE OPENSSL_LIBRARY_DEBUG
                 OPENSSL_CRYPTO_LIBRARY_RELEASE OPENSSL_CRYPTO_LIBRARY_DEBUG)
